server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para la API de Despachos
    location /api/v1/despachos {
        proxy_pass http://backend-app:8081; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy para la API de Ventas
    location /api/v1/ventas {
        proxy_pass http://backend-app:8082; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}